# this is a toml 

title = "config for https://github.com/soapffz/feeddd-to-cubox"

[cubox]
api = "sdasdasda"
defaulttag = "newview"
threads = 100
blwxpbcount = "网罗灯下黑,王者荣耀,中国新闻周刊,新华社,搞机猿,WileyChem,新型储能电池,ScienceAAAS,陶白白"
blwxpbcountkeywords = "证券,财经,理财,银行,医院,联通,电信,移动,生态环境,发布,就业,考试,招聘,公司,保险,考试吧,推荐,资源,一起学,服务号,考试院,考研,营销,助手,协会,广播,资讯,一点,妇幼,保健院,本地宝,住房和建设局,备考,咨询,房产,MBA,实习,浏览器,材料网,商会,招生办,大学,俱乐部,总领馆,应急管理部,日报,晚报,本地通,照明,化学,电池,Science"
blwxarticlekeywords = "招聘,多功能,很关键,你还不会,当心,直播预告,就业班,下载,offer,绝了,免费,重磅,紧急,新增,报备,加州,点击查看,前所未有,住宅成交,新房,收藏,缺口,首个,突破,去向何方,美国,慈善,成人,白皮书,私域,开除,裁员,贸易,恒大,化学,新增,习近平,电池,资金,币圈,利空,金融,债劵,陨石,出任,逝世,壁纸,被查,履新"