# this is a toml 

title = "config for https://github.com/soapffz/feeddd-to-cubox"

[cubox]
api = "sdasdasda"
defaulttag = "newview"
threads = 100
blwxpbcount = "网罗灯下黑,王者荣耀,中国新闻周刊,新华社,搞机猿,WileyChem,新型储能电池,陶白白,鹿头社,保二爷,哔哩哔哩,财新网,36氪,印象笔记,中国国家历史,中科院之声,原理,包邮区,仲易说,胡子球手,工控小师妹,陆家嘴大宗商品论坛"
blwxpbcountkeywords = "证券,财经,理财,银行,医院,联通,电信,移动,生态环境,发布,就业,考试,招聘,公司,保险,考试吧,推荐,一起学,服务号,考试院,考研,营销,助手,协会,广播,资讯,一点,妇幼,保健院,本地宝,住房和建设局,备考,咨询,房产,MBA,实习,浏览器,材料网,商会,招生办,大学,俱乐部,总领馆,应急管理部,日报,晚报,本地通,照明,化学,电池,Science,股份,能源,量子,论文,思想,聚焦,环球,周刊,人文,历史,易经,头条,工业"
blwxarticlekeywords = "招聘,多功能,很关键,你还不会,当心,直播预告,就业班,下载,offer,绝了,免费,重磅,紧急,新增,报备,加州,点击查看,前所未有,住宅成交,新房,收藏,缺口,首个,突破,去向何方,美国,慈善,成人,白皮书,私域,开除,裁员,贸易,恒大,化学,习近平,电池,资金,币圈,利空,金融,债劵,陨石,出任,逝世,壁纸,被查,履新,诈骗,被骗,自查,转发,召开,博士,税后,安家费,聚集性,诚聘,锂,迎来,色谱,光谱,主持召开,二十大,直博,材料,光伏,催化,科研,甲虫,蜂,研究,财务自由,论文,投稿,受贿,一审,开庭,减持,卸任,董事,波兰,袭击,大运河,新加坡,澳大利亚,好货,熊市,利好,融资,地产,A股,美联储,油价,债市,全款,恭喜了,限招,首付,封闭,首款,面相,展会,镍,元宇宙,虚幻,Unity,引擎,哈登,高通,骁龙,新闻联播,电气,电工,华为,创业,留美,北美,租房,北京,中介,房东,直租"